import { ThemeProvider } from "@/components/layout/theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";
import { CodeConfigStoreProvider } from "@/stores/code-config/provider";
import type { Metadata } from "next";
import { Inter, JetBrains_Mono, Playfair_Display } from "next/font/google";

import { CodeProvider } from "@/hooks/use-code";
import "@/styles/globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const fontSerif = Playfair_Display({
    subsets: ["latin"],
    variable: "--font-serif",
});

const fontMono = JetBrains_Mono({
    subsets: ["latin"],
    variable: "--font-mono",
});

export const metadata: Metadata = {
    title: "QReate",
    // description: "Generated by create next app",
};

export default function RootLayout({ children }: React.PropsWithChildren) {
    return (
        <html lang="en" suppressHydrationWarning className={cn("font-sans", inter.variable)}>
            <head>
                <meta name="apple-mobile-web-app-title" content="QReate" />
            </head>

            <body className={`${inter.variable} ${fontSerif.variable} ${fontMono.variable} antialiased`}>
                <CodeConfigStoreProvider>
                    <ThemeProvider>
                        <TooltipProvider>
                            <CodeProvider>{children}</CodeProvider>
                        </TooltipProvider>
                    </ThemeProvider>
                </CodeConfigStoreProvider>
            </body>
        </html>
    );
}
